/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */
import { bundesliga, pl, laliga, sony } from "../../assets";
export const videos = [
  {
    _id: "Wo5dMEP_BbB",
    title: "Jamal Musiala |Bundesliga's Best",
    videoLength: "03:13",
    youtubeID: "IHLJ_tQboe4",
    thumbnail: "http://i3.ytimg.com/vi/IHLJ_tQboe4/hqdefault.jpg",
    viewCount: "19k views",
    channelName: "Bundesliga",
    channelImg: bundesliga,
    category: "Bundesliga",
  },
  {
    _id: "Wo5dMEP_BbC",
    title:
      "Last-Second-Spectacle | Borussia Dortmund | FC Bayern München 2-2 | All Goals | MD 9 | Bundesliga",
    videoLength: "01:10",
    youtubeID: "P4fyi6A5unk",
    thumbnail: "http://i3.ytimg.com/vi/P4fyi6A5unk/hqdefault.jpg",
    viewCount: "120k views",
    channelName: "Bundesliga",
    channelImg: bundesliga,
    category: "Bundesliga",
  },
  {
    _id: "Wo5dMEP_BbD",
    title: "Christopher Nkunku • All Bundesliga Goals Ever",
    videoLength: "06:03",
    youtubeID: "0ryedx9-enE",
    thumbnail: "http://i3.ytimg.com/vi/0ryedx9-enE/hqdefault.jpg",
    viewCount: "40k views",
    channelName: "Bundesliga",
    channelImg: bundesliga,
    category: "Bundesliga",
  },
  {
    _id: "Wo5dMEP_BbF",
    title: "Chelsea vs AC Milan Match Highlights | UCL | Sony Sports Network",
    videoLength: "04:04",
    youtubeID: "XM3mEMyS9UI",
    thumbnail: "http://i3.ytimg.com/vi/XM3mEMyS9UI/hqdefault.jpg",
    viewCount: "800k views",
    channelName: "Sony Sports Network",
    channelImg: sony,
    category: "Champions League",
  },
  {
    _id: "Wo5dMEP_BbG",
    title:
      "Benfica 1- 1 PSG | Highlights | UEFA Champions League | 6th October 2022",
    videoLength: "09:01",
    youtubeID: "RsutIpD-Qkc",
    thumbnail: "http://i3.ytimg.com/vi/RsutIpD-Qkc/hqdefault.jpg",
    viewCount: "70k views",
    channelName: "Sony Sports Network",
    channelImg: sony,
    category: "Champions League",
  },

  {
    _id: "Wo5dMEP_BbE",
    title: "Leroy Sané | Bundesliga's Best",
    videoLength: "08:18",
    youtubeID: "5aeT6xdMhZY",
    thumbnail: "http://i3.ytimg.com/vi/5aeT6xdMhZY/hqdefault.jpg",
    viewCount: "30k views",
    channelName: "Bundesliga",
    channelImg: bundesliga,
    category: "Bundesliga",
  },
  {
    _id: "Wo5dMEP_BbH",
    title:
      "Manchester City vs FC Copenhagen Match Highlights | UCL | Sony Sports Network",
    videoLength: "04:04",
    youtubeID: "sARApMckQcM",
    thumbnail: "http://i3.ytimg.com/vi/sARApMckQcM/hqdefault.jpg",
    viewCount: "30k views",
    channelName: "Sony Sports Network",
    channelImg: sony,
    category: "Champions League",
  },
  {
    _id: "Wo5dMEP_BbI",
    title:
      "Real Madrid 2 - 1 Shakhtar Donetsk | Highlights | UEFA Champions League | 6th October 2022",
    videoLength: "08:36",
    youtubeID: "bCIuT3MSX1I",
    thumbnail: "http://i3.ytimg.com/vi/bCIuT3MSX1I/hqdefault.jpg",
    viewCount: "10k views",
    channelName: "Sony Sports Network",
    channelImg: sony,
    category: "Champions League",
  },
  {
    _id: "Wo5dMEP_BbJ",
    title: "Highlights Getafe CF vs Real Madrid (0-1)",
    videoLength: "07:36",
    youtubeID: "WR50CwIXeGs",
    thumbnail: "http://i3.ytimg.com/vi/WR50CwIXeGs/hqdefault.jpg",
    viewCount: "110k views",
    channelName: "La Liga",
    channelImg: laliga,
    category: "La Liga",
  },
  {
    _id: "Wo5dMEP_BbK",
    title:
      "Newcastle United 5 Brentford 1 | EXTENDED Premier League Highlights",
    videoLength: "10:05",
    youtubeID: "NfGNeJ6Dm7Y",
    thumbnail: "http://i3.ytimg.com/vi/NfGNeJ6Dm7Y/hqdefault.jpg",
    viewCount: "250k views",
    channelName: "Premeier League",
    channelImg: pl,
    category: "Pl",
  },
  {
    _id: "Wo5dMEP_BbL",
    title: "Highlights Atlético de Madrid vs Girona FC (2-1)",
    videoLength: "03:04",
    youtubeID: "md_An_8YZII",
    thumbnail: "http://i3.ytimg.com/vi/md_An_8YZII/hqdefault.jpg",
    viewCount: "150k views",
    channelName: "La Liga",
    channelImg: laliga,
    category: "La Liga",
  },
  {
    _id: "Wo5dMEP_BbM",
    title: "Chelsea 3-0 Wolves | Premier League Highlights",
    videoLength: "02:02",
    youtubeID: "TQkZArlY76U",
    thumbnail: "http://i3.ytimg.com/vi/TQkZArlY76U/hqdefault.jpg",
    viewCount: "1.3M views",
    channelName: "Premeier League",
    channelImg: pl,
    category: "Pl",
  },
];
